version: 2
registries:
  rubygems-server-nexus-devops-citizensadvice-org-uk-repository-ca:
    type: rubygems-server
    url: https://nexus.devops.citizensadvice.org.uk/repository/ca-gems
    username: "${{secrets.RUBYGEMS_SERVER_NEXUS_DEVOPS_CITIZENSADVICE_ORG_UK_REPOSITORY_CA_USERNAME}}"
    password: "${{secrets.RUBYGEMS_SERVER_NEXUS_DEVOPS_CITIZENSADVICE_ORG_UK_REPOSITORY_CA_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: hamlit
    versions:
    - 2.14.3
    - 2.14.4
    - 2.14.6
  - dependency-name: sinatra
    versions:
    - 2.1.0
  - dependency-name: byebug
    versions:
    - 11.1.3
  - dependency-name: faraday
    versions:
    - 1.3.0
  - dependency-name: rack
    versions:
    - 2.2.3
  registries:
  - rubygems-server-nexus-devops-citizensadvice-org-uk-repository-ca
