version: "3"

services:
  app:
    build: .
    image: "citizensadvice/sns-email-notification-mocker"
    ports:
      - 4001:4000
    volumes:
      - .:/app
    environment:
      - ENDPOINT=http://localhost:4000/debug
